### ISSUE TITLE
Error ejemplo Sustitución HTML  en JavaScript.md

### ISSUE THREAD

**Issue by linares-it** [rubnvp/vue-pokedex#1]
Hola Rubén:
  
     Por favor revisar el ejemplo de sustitución de HTML del archivo "JavaScript.md".  donde dice:
  
     "COLOR[pokemon.types[0]]}"

      debería decir:

      "typeColor[pokemon.types[0]]"

        tal como está, en la consola del navegador indica: "ReferenceError: COLOR is not defined"

**Comment by rubnvp** [comment]
Solucionado en https://github.com/rubnvp/vue-pokedex/commit/5af839a0910a84ba3a0e7f0f5ad10c00cd7cf3a0
Muchas gracias @eduardolinaresp ! 😄
