### ISSUE TITLE
Chuleta para el taller

### ISSUE THREAD

**Issue by baumannzone** [rubnvp/vue-pokedex#2]
https://www.vuemastery.com/pdf/Vue-Essentials-Cheat-Sheet.pdf

![image](https://user-images.githubusercontent.com/5422102/69425236-db76b980-0d2a-11ea-94b7-79c91d2be74b.png)

**Comment by rubnvp** [comment]
mola, lo meto, gracias! 😄

**Comment by baumannzone** [comment]
A buenas horas XDD

**Comment by rubnvp** [comment]
jajaja, no me llegó la notificación en su momento parece 😅
